apiVersion: v1
kind: Service
metadata:
  name: argocd-server-nodeport
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-server-nodeport
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30808
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
    nodePort: 30843
  selector:
    app.kubernetes.io/name: argocd-server