# Traefik Helm values for k3s with NodePort (10.0.0.88)
deployment:
  replicas: 1

service:
  type: NodePort

ports:
  web:
    port: 80
    nodePort: 30080
    expose: 
      default: true
  websecure:
    port: 443
    nodePort: 30443
    expose:
      default: true
  traefik:
    port: 9000
    nodePort: 30900
    expose:
      default: true

ingressRoute:
  dashboard:
    enabled: true

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  traefik:
    address: ":9000"

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 128Mi

globalArguments:
  - "--global.checknewversion=false"
  - "--global.sendanonymoususage=false"