apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: /home/davidg/k8s-devops-pipeline/gitops
    targetRevision: HEAD
    path: environments/dev/nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true