apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sample
  namespace: sample-apps
  labels:
    app: nginx-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-sample
  template:
    metadata:
      labels:
        app: nginx-sample
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-sample-service
  namespace: sample-apps
spec:
  type: NodePort
  selector:
    app: nginx-sample
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080