name: Infrastructure Deployment

on:
  push:
    paths:
      - 'manifests/**'
      - 'gitops/infrastructure/**'
    branches: [main]
  workflow_dispatch:

env:
  KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}

jobs:
  validate-manifests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.0'
        
    - name: Validate Kubernetes manifests
      run: |
        find manifests/ -name "*.yaml" -exec kubectl apply --dry-run=client -f {} \;
        
    - name: Lint YAML files
      uses: ibiqlik/action-yamllint@v3
      with:
        config_file: .yamllint.yml
        file_or_dir: manifests/
        
  deploy-infrastructure:
    runs-on: ubuntu-latest
    needs: validate-manifests
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure kubeconfig
      run: |
        echo "${{ env.KUBECONFIG_FILE }}" | base64 -d > kubeconfig
        export KUBECONFIG=./kubeconfig
        
    - name: Deploy Phase 2 Infrastructure
      run: |
        make deploy-all
        
    - name: Deploy ArgoCD
      run: |
        kubectl apply -f manifests/argocd/
        
    - name: Verify deployment
      run: |
        make status
        make verify